<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCZdpbFQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCZdpbFQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCZdpbFQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCZdpbFQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCZdpbFQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'CZdpbFQ',
    'container.build_id' => '7606dd1c',
    'container.build_time' => 1764853936,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCZdpbFQ');
